# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google-authsub}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stuart Coyle", "Jesse Storimer"]
  s.date = %q{2010-01-22}
  s.description = %q{GoogleAuthSub provides the Google Authentications for Web Applications API.}
  s.email = %q{stuart.coyle@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "coverage/-Library-Ruby-Gems-1_8-gems-FakeWeb-1_1_2-lib-fake_net_http_rb.html",
     "coverage/-Library-Ruby-Gems-1_8-gems-FakeWeb-1_1_2-lib-fake_web_rb.html",
     "coverage/-Library-Ruby-Gems-1_8-gems-rcov-0_8_1_2_0-lib-rcov_rb.html",
     "coverage/index.html",
     "coverage/lib-googleauthsub_rb.html",
     "coverage/spec-googleauthsub_spec_rb.html",
     "coverage/spec-spec_helper_rb.html",
     "doc/classes/AuthEchoServlet.html",
     "doc/classes/AuthEchoServlet.src/M000001.html",
     "doc/classes/AuthEchoServlet.src/M000002.html",
     "doc/classes/GData.html",
     "doc/classes/GData/AuthSubError.html",
     "doc/classes/GData/AuthSubError.src/M000019.html",
     "doc/classes/GData/Error.html",
     "doc/classes/GData/GoogleAuthSub.html",
     "doc/classes/GData/GoogleAuthSub.src/M000001.html",
     "doc/classes/GData/GoogleAuthSub.src/M000002.html",
     "doc/classes/GData/GoogleAuthSub.src/M000003.html",
     "doc/classes/GData/GoogleAuthSub.src/M000004.html",
     "doc/classes/GData/GoogleAuthSub.src/M000005.html",
     "doc/classes/GData/GoogleAuthSub.src/M000006.html",
     "doc/classes/GData/GoogleAuthSub.src/M000007.html",
     "doc/classes/GData/GoogleAuthSub.src/M000008.html",
     "doc/classes/GData/GoogleAuthSub.src/M000009.html",
     "doc/classes/GData/GoogleAuthSub.src/M000010.html",
     "doc/classes/GData/GoogleAuthSub.src/M000011.html",
     "doc/classes/GData/GoogleAuthSub.src/M000012.html",
     "doc/classes/GData/GoogleAuthSub.src/M000013.html",
     "doc/classes/GData/GoogleAuthSub.src/M000014.html",
     "doc/classes/GData/GoogleAuthSub.src/M000015.html",
     "doc/classes/GData/GoogleAuthSub.src/M000016.html",
     "doc/classes/GData/GoogleAuthSub.src/M000017.html",
     "doc/classes/GData/GoogleAuthSub.src/M000018.html",
     "doc/created.rid",
     "doc/files/googleauthsub_rb.html",
     "doc/files/lib/googleauthsub_rb.html",
     "doc/files/spec/googleauthsub_spec_rb.html",
     "doc/files/spec/googleresponder_rb.html",
     "doc/files/spec/spec_helper_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "google-authsub-0.0.2.gem",
     "google-authsub-0.0.3.gem",
     "google-authsub.gemspec",
     "lib/googleauthsub.rb",
     "live test/authsub_test.html",
     "live test/gastest.rb",
     "spec/googleauthsub_spec.rb",
     "spec/googleresponder.rb",
     "spec/mock responses/bad_token_info.txt",
     "spec/mock responses/calendar.txt",
     "spec/mock responses/revoke_token.txt",
     "spec/mock responses/revoked_token.txt",
     "spec/mock responses/session_token.txt",
     "spec/mock responses/token_info.txt",
     "spec/mock responses/unauthorized.txt",
     "spec/mock_certs/test_private_key.pem",
     "spec/mock_certs/test_public_key.pem",
     "spec/spec_helper.rb",
     "spec/spec_opts"
  ]
  s.homepage = %q{http://github.com/stuart/google-authsub/tree/master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A ruby implementation of Google Authentication for Web Applications API}
  s.test_files = [
    "spec/googleauthsub_spec.rb",
     "spec/googleresponder.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

